#Configurations for system MOTD.
system:
  #Do you want the system MOTD to be enabled? Set this to false if you don't want this.
  enabled: true
  #The system MOTD that will be visible to players when they refresh their server list.
  #%VERSION% gets replaced with the version of the server. Note that this feature may be a bit unstable.
  motd:

    #These are the MOTDs when the server is not whitelisted.
    normal:
      - "Rumblur Classic"
      - "We are testing random MOTD!"
    #- "Another MOTD here"


    #These are the MOTDs which shows up when the server is whitelisted.
    whitelist:
      - "&4The server is currently whitelisted!&r\nPlease come back later."
      - "Hey you can't play here since the server is whitelisted for a while."
    #  - "Another MOTD here"